language: c++

matrix:	
  include:
    -os: linux
    dist: trusty
    sudo: required
    env: CC=mpicc CXX=mpic++


	

script:
  - git clone -b stable https://github.com/lammps/lammps.git
  - make serial
